config/routes.rb
CodeCampo::Application.routes.draw do
  root :to => 'homepage#index'

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users, :only => [:create, :destroy]

  resources :user_sessions, :only => [:create]

  resource :search, :controller => 'search', :only => 'show'

  get '~:name', :controller => 'people', :action => 'show', :as => :person
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end
  resources :topics, :only => [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :newest
      get :my
      get :marked
      get :replied
      get 'tagged/:tag', :action => 'tagged', :as => :tagged, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get :interesting
    end
    member do
      post :mark
      delete :mark, :action => 'unmark'
    end
  end
  resources :replies, :only => [:new, :create, :edit, :update]
  namespace :settings do
    resource :account, :only => [:show, :update]
    resource :password, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end

  namespace :admin do
    get '/', :to => 'dashboard#show', :as => 'dashboard'
    resources :fragments, :only => [:index, :edit, :update]
    resource  :site, :only => [:show, :update]
    resources :users, :only => [:index, :show, :destroy]
    resources :topics, :only => [:index, :show, :destroy]
    resources :replies, :only => [:index, :show, :destroy]
  end
end

app/models/topic.rb
class Topic
  include Mongoid::Document
  include Mongoid::Timestamps::Created
  include Mongoid::NumberId
  include Mentionable

  field :title
  field :content
  field :tags,               :type => Array,   :default => []
  field :actived_at,         :type => Time
  field :edited_at,          :type => Time
  field :replies_count,      :type => Integer, :default => 0
  field :marker_ids,         :type => Array,   :default => []
  field :replier_ids,        :type => Array,   :default => []
  field :last_read_user_ids, :type => Array,   :default => []

  belongs_to :user
  belongs_to :last_reply_user, :class_name => 'User'
  has_many   :replies, :dependent => :delete

  validates :title, :content, :user, :presence => true
  validates :tag_string, :tag_string => true, :format => { :with => /\A[^\/]+\z/, :message => I18n.t("errors.no_allow_slash"), :allow_blank => true}

  before_create :set_actived_at

  attr_accessible :title, :content, :tag_string

  scope :active, order_by([[:actived_at, :desc]])
  scope :mark_by, lambda {|user| where(:marker_ids => user.id)}
  scope :reply_by, lambda {|user| where(:replier_ids => user.id)}

  def tag_string=(string)
    self.tags = string.to_s.downcase.split(/[,\s]+/).uniq
  end

  def tag_string
    self.tags.join(', ')
  end

  def set_actived_at
    self.actived_at = Time.now.utc
  end

  def set_edited_at
    self.edited_at = Time.now.utc
  end

  def edited?
    edited_at.present?
  end

  def last_page
    page = (replies_count.to_f / self.class.default_per_page).ceil
    page > 1 ? page : nil
  end

  def anchor
    "topic-#{number_id}"
  end

  def relate_topics(count)
    Topic.active.any_in(:tags => tags).limit(count).where(:_id.ne => id)
  end

  def mark_by(user)
    unless marked_by? user
      collection.update({:_id => self.id},
                        {"$addToSet" => {:marker_ids => user.id}})
      marker_ids.push user.id
    end
  end

  def unmark_by(user)
    if marked_by? user
      collection.update({:_id => self.id},
                        {"$pull" => {:marker_ids => user.id}})
      marker_ids.delete user.id
    end
  end

  def marked_by?(user)
    marker_ids.include? user.id
  end

  def marker_count
    marker_ids.count
  end

  def reply_by(user)
    unless replied_by?(user) || self.user == user
      collection.update({:_id => self.id},
                        {"$addToSet" => {:replier_ids => user.id}})
    end
  end

  def replied_by?(user)
    replier_ids.include? user.id
  end

  def update_reply_stats_by(reply)
    self.actived_at = reply.created_at
    self.last_reply_user = reply.user
    save
  end

  def reset_reply_stats
    last_reply = replies.order([[:created_at, :asc]]).last
    if last_reply
      update_reply_stats_by(last_reply)
    else
      self.actived_at = created_at
      self.last_reply_user = nil
      save
    end
  end

  def last_read?(user)
    last_read_user_ids.include? user.id
  end

  def read_by(user)
    unless last_read?(user)
      add_to_set(:last_read_user_ids, user.id)
    end
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::BaseController
  before_filter :find_topic, :except => :index

  def index
    @topics = Topic.order_by([:created_at, :desc]).page(params[:page])
  end

  def show
  end

  def destroy
    @topic.destroy
    flash[:success] = I18n.t('admin.topics.destroy.delete_success', :title => @topic.title)
    redirect_to :action => :index
  end

  protected

  def find_topic
    @topic = Topic.number(params[:id])
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_filter :old_id_redirect, :only => [:show]
  before_filter :require_logined, :except => [:index, :show, :tagged, :newest]
  before_filter :find_topic, :only => [:show, :mark, :unmark]
  before_filter :find_user_topic, :only => [:edit, :update]

  def index
    @topics = Topic.active.page(params[:page])
  end

  def newest
    respond_to do |format|
      format.html do
        @topics = Topic.order_by([[:created_at, :desc]]).page(params[:page])
        render :index
      end
      format.rss do
        @topics = Topic.order_by([[:created_at, :desc]]).limit(20)
        @page_title = I18n.t('newest_topics_title', :site_name => @site.name)
        render :index, :layout => false
      end
    end
  end

  def my
    @topics = current_user.topics.active.page(params[:page])
    render :index
  end

  def marked
    @topics = Topic.mark_by(current_user).active.page(params[:page])
    render :index
  end

  def replied
    @topics = Topic.reply_by(current_user).active.page(params[:page])
    render :index
  end

  def tagged
    respond_to do |format|
      format.html do
        @topics = Topic.where(:tags => params[:tag]).active.page(params[:page])
        render :index
      end
      format.rss do
        @topics = Topic.where(:tags => params[:tag]).order_by([[:created_at, :desc]]).limit(20)
        @page_title = I18n.t('tagged_newest_topics', :site_name => @site.name, :tag => params[:tag])
        render :index, :layout => false
      end
    end
  end

  def new
    @topic = Topic.new :tag_string => params[:tag]
  end

  def create
    @topic = current_user.topics.new params[:topic]
    if @topic.save
      redirect_to @topic
    else
      render :new
    end
  end

  def show
    @replies = @topic.replies.page(params[:page])

    if logined?
      if !@topic.last_read?(current_user) && current_user.notifications.has_unread?
        current_user.notifications.unread.any_of({:mentionable_type => 'Topic', :mentionable_id => @topic.id},
                                                 {:mentionable_type => 'Reply', :mentionable_id.in => @replies.map(&:id)},
                                                 {:reply_id.in => @replies.map(&:id)}).update_all(:read => true)
      end
      @topic.read_by current_user
      @reply = current_user.replies.new :topic => @topic
    end

    @relate_topics = @topic.relate_topics(5)
  end

  def edit
  end

  def update
    @topic.set_edited_at
    if @topic.update_attributes params[:topic]
      redirect_to @topic
    else
      render :edit
    end
  end

  def mark
    @topic.mark_by current_user
    respond_to do |format|
      format.html { redirect_referrer_or_default @topic }
      format.js { render :layout => false }
    end
  end

  def unmark
    @topic.unmark_by current_user
    respond_to do |format|
      format.html { redirect_referrer_or_default @topic }
      format.js { render :mark, :layout => false }
    end
  end

  protected

  def find_topic
    @topic = Topic.number(params[:id])
  end

  def find_user_topic
    @topic = current_user.topics.number(params[:id])
  end

  # TODO remove
  def old_id_redirect
    if params[:id] !~ /\A\d+\z/
      topic = Topic.first :conditions => {:_id => params[:id]}
      redirect_to(topic, :status => 301) if topic
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def subscribe_url
    case action_name
    when 'index', 'newest'
      newest_topics_url(:format => :rss)
    when 'tagged'
      tagged_topics_url(:format => :rss, :tag => params[:tag])
    end
  end
end

app/views/topics/_form.haml
.control-group
  .full-input-wrap= form.text_field :title, :validate => false, :placeholder => t('.title_placeholder')
.control-group
  #editor-button-bar
  .full-input-wrap= form.text_area :content, :id => 'editor-input', :rows => 20, :validate => false
  #editor-preview
.control-group
  .full-input-wrap= form.text_field :tag_string, :data => {:suggest => Tag.suggest_tags}, :placeholder => t('.tags_placeholder')

app/views/topics/_marks_count.haml
%span.marks_count
  - if logined?
    - if topic.marked_by?(current_user)
      = link_to t('.marked'), mark_topic_path(topic), :method => :delete, :remote => true
    - else
      = link_to t('.mark'), mark_topic_path(topic), :method => :post, :remote => true
  - if topic.marker_count > 0
    = t '.marker_count', :count => topic.marker_count

app/views/topics/_topic.haml
%tr{:id => topic.anchor}
  %td.avatar
    = link_avatar_to_person(topic.user)
  %td.content
    %h3
      = link_to topic.title, topic_path(topic, :page => topic.last_page)
    .info
      - if topic.tags.to_a.any?
        %span.tags
          - topic.tags.each do |tag|
            = link_to tag, tagged_topics_path(:tag => tag)
      %span.author
        = link_to_person(topic.user)
      %span.time
        = t 'created_at'
        = format_time topic.created_at
        - if topic.replies_count > 0
          ,
          = link_to_person(topic.last_reply_user)
          = t 'replied_at'
          = format_time topic.actived_at
  %td.reply-count.last
    - if topic.replies_count > 0
      = link_to topic.replies_count, topic_path(topic, :page => topic.last_page), :class => ((logined? && topic.last_read?(current_user)) ? 'read' : nil)

app/views/topics/edit.haml
- @page_title = "#{t('edit')}#{t('.topics')}"

- content_for :head do
  = javascript_include_tag 'editor'
  = stylesheet_link_tag 'editor'

#main
  .container
    .row
      .span12
        %ul.breadcrumb
          %li
            = link_to t('.topics'), topics_path
            %span.divider /
          %li
            = link_to @topic.title, @topic
            %span.divider /
          %li.active
            = t('edit')

    .row
      #mainbar.span9
        %section#editor.box
          = form_for @topic, :validate => true do |f|
            = render :partial => 'form', :object => f
            .control-group= f.submit t('update'), :class => 'btn primary'
      #sidebar.span3
        = render :partial => 'shared/sidebar_profile'

app/views/topics/index.haml
- if action_name == 'index'
  - @page_title = t('.topics')
- elsif action_name == 'tagged'
  - @page_title = "#{t('.tagged', :tag => params[:tag])} - #{t('.topics')}"
- else
  - @page_title = "#{t(".#{action_name}")} - #{t('.topics')}"

- @subscribe_url = subscribe_url

#main
  .container
    .row
      .span12
        %ul.breadcrumb
          %li
            = link_to t('.topics'), topics_path
            %span.divider /
          %li.active
            - if action_name == 'tagged'
              = t '.tagged', :tag => params[:tag]
            - else
              = t ".#{action_name}"
    .row
      #mainbar.span9
        - if @topics.any?
          %section#topics.box.no-padding
            %table.item-list
              %tbody
                = render :partial => 'topic', :collection => @topics
          = paginate @topics
        - else
          %section.box
            = t '.no_topics'
      #sidebar.span3
        - if logined?
          = render :partial => 'shared/sidebar_profile'
          %section.box
            - if action_name == 'tagged'
              = link_to t('.create_topic'), new_topic_path(:tag => params[:tag]), :class => 'btn btn-primary'
            - else
              = link_to t('.create_topic'), new_topic_path, :class => 'btn btn-primary'
        - else
          = render :partial => 'shared/sidebar_login'
        - if %w(index newest tagged).include?(action_name)
          %section.box
            %header= t('.subscribe')
            = link_to image_tag('rss.png'), subscribe_url
        = raw @site.fragment.topics_sidebar_bottom

app/views/topics/mark.js.erb
(function(){
  var $topic = $('#' + '<%= @topic.anchor %>');
  $topic.find('.marks_count').replaceWith('<%= escape_javascript(render :partial => 'marks_count', :locals => {:topic => @topic}) %>');
})();

app/views/topics/new.haml
- content_for :head do
  = javascript_include_tag 'editor'
  = stylesheet_link_tag 'editor'

- @page_title = t('.create_topic')

#main
  .container
    .row
      .span12
        %ul.breadcrumb
          %li
            = link_to t('.topics'), topics_path
            %span.divider /
          %li.active= t('.create_topic')
    .row
      #mainbar.span9
        %section#editor.box
          = form_for @topic, :validate => true do |f|
            = render :partial => 'form', :object => f
            .control-group= f.submit t('submit'), :class => 'btn primary'
      #sidebar.span3
        = render :partial => 'shared/sidebar_profile'

app/views/topics/show.haml
- @page_title = "#{@topic.title} - #{t('.topics')}"

- if logined?
  - content_for :head do
    = javascript_include_tag 'editor'
    = stylesheet_link_tag 'editor'
    = javascript_include_tag 'topics/show'

#main
  .container
    .row
      .span12
        %ul.breadcrumb
          %li
            = link_to t('.topics'), topics_path
            %span.divider /
          %li.active= @topic.title
    .row
      #mainbar.span9
        %section#topic.box
          %article{:id => @topic.anchor}
            %header
              %table
                %tbody
                  %tr
                    %td
                      %h1= @topic.title
                      - if @topic.tags && @topic.tags.any?
                        %span.tags
                          - @topic.tags.each do |tag|
                            = link_to tag, tagged_topics_path(:tag => tag)
                      %span.author
                        = link_to_person @topic.user
                      %span.time
                        = t('created_at')
                        = format_time @topic.created_at
                        - if @topic.edited?
                          = t('updated_at')
                          = format_time @topic.edited_at
                      - if logined? && current_user == @topic.user
                        = link_to t('edit'), edit_topic_path(@topic)
                    %td.avatar
                      = link_to image_tag(@topic.user.gravatar_url(:size => 72)), person_path(@topic.user)
            ~ format_text @topic.content, :mention_names => @topic.mentioned_user_names
            %footer
              = render :partial => 'marks_count', :locals => {:topic => @topic}
        %section#replies.box.no-padding
          %table.item-list
            %tbody
              = render :partial => 'replies/reply', :collection => @replies
        = paginate @replies
        - if logined?
          %section#editor.box
            %h4= t('.post_reply')
            = form_for @reply, :url => replies_path(:topic_id => @topic), :remote => true do |f|
              = render :partial => 'replies/form', :object => f
              .control-group= f.submit t('submit'), :class => 'btn primary', :data => {:disable_with => t('form_disable_with')}

      #sidebar.span3
        - if logined?
          = render :partial => 'shared/sidebar_profile'
        %section.box
          %header
            = t('.relate_topics')
          .content
            - if @relate_topics.any?
              %ul.nice-list
                - @relate_topics.each do |topic|
                  %li= link_to topic.title, topic
            - else
              = t('.no_relate_topics')