config/routes.rb
CodeCampo::Application.routes.draw do
  root :to => 'homepage#index'

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users, :only => [:create, :destroy]

  resources :user_sessions, :only => [:create]

  resource :search, :controller => 'search', :only => 'show'

  get '~:name', :controller => 'people', :action => 'show', :as => :person
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end
  resources :topics, :only => [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :newest
      get :my
      get :marked
      get :replied
      get 'tagged/:tag', :action => 'tagged', :as => :tagged, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get :interesting
    end
    member do
      post :mark
      delete :mark, :action => 'unmark'
    end
  end
  resources :replies, :only => [:new, :create, :edit, :update]
  namespace :settings do
    resource :account, :only => [:show, :update]
    resource :password, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end

  namespace :admin do
    get '/', :to => 'dashboard#show', :as => 'dashboard'
    resources :fragments, :only => [:index, :edit, :update]
    resource  :site, :only => [:show, :update]
    resources :users, :only => [:index, :show, :destroy]
    resources :topics, :only => [:index, :show, :destroy]
    resources :replies, :only => [:index, :show, :destroy]
  end
end

app/models/notification/base.rb
class Notification::Base
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  store_in :notifications

  field :read, :default => false

  scope :unread, where(:read => false)

  belongs_to :user

  def anchor
    "notification-#{id}"
  end
end

app/models/notification/mention.rb
class Notification::Mention < Notification::Base
  belongs_to :mentionable, :polymorphic => true

  validates :mentionable, :presence => true
end

app/models/notification/topic_reply.rb
class Notification::TopicReply < Notification::Base
  belongs_to :reply

  validates :reply, :presence => true
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_filter :require_logined

  def index
    @notifications = current_user.notifications.order_by([[:created_at, :desc]]).page(params[:page]).cache
    current_user.read_notifications(@notifications)
  end

  def mark_all_as_read
    current_user.mark_all_notifications_as_read
    respond_to do |format|
      format.html { redirect_referrer_or_default notifications_path }
      format.js { render :layout => false }
    end
  end

  def destroy
    @notification = current_user.notifications.find params[:id]
    @notification.destroy
    respond_to do |format|
      format.html { redirect_referrer_or_default notifications_path }
      format.js { render :layout => false }
    end
  end
end

app/views/notifications/destroy.js.erb
(function() {
  $('#' + '<%= @notification.anchor %>').fadeOut('normal', function(){
    $(this).remove();
  });
})()

app/views/notifications/index.haml
#main
  .container
    .row
      #mainbar.span9
        - if @notifications.any?
          %section.box#notifications.no-padding
            %table.item-list
              %tbody
                - @notifications.each do |notification|
                  %tr{:id => notification.anchor}
                    = render :partial => "notifications/#{notification.class.name.underscore}", :locals => {:notification => notification}
                    %td.last
                      = link_to '×', notification_path(notification), :class => 'close', :method => :delete, :remote => true
          = paginate @notifications
        - else
          %section.box
            = t '.no_notifications'
      #sidebar.span3
        = render :partial => 'shared/sidebar_profile'
        %section.box
          = button_to t('.mark_all_as_read'), mark_all_as_read_notifications_path, :class => 'btn', :data => {:disable_with => t('.marking')}, :remote => true, :method => :put

app/views/notifications/mark_all_as_read.js.erb
(function() {
  $('#sidebar .notifications a').addClass('read').find('.count').text('0');
  $('#notifications span.new').fadeOut('fast', function(){
    $(this).remove();
  });
})()