config/routes.rb
CodeCampo::Application.routes.draw do
  root :to => 'homepage#index'

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users, :only => [:create, :destroy]

  resources :user_sessions, :only => [:create]

  resource :search, :controller => 'search', :only => 'show'

  get '~:name', :controller => 'people', :action => 'show', :as => :person
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end
  resources :topics, :only => [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :newest
      get :my
      get :marked
      get :replied
      get 'tagged/:tag', :action => 'tagged', :as => :tagged, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get :interesting
    end
    member do
      post :mark
      delete :mark, :action => 'unmark'
    end
  end
  resources :replies, :only => [:new, :create, :edit, :update]
  namespace :settings do
    resource :account, :only => [:show, :update]
    resource :password, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end

  namespace :admin do
    get '/', :to => 'dashboard#show', :as => 'dashboard'
    resources :fragments, :only => [:index, :edit, :update]
    resource  :site, :only => [:show, :update]
    resources :users, :only => [:index, :show, :destroy]
    resources :topics, :only => [:index, :show, :destroy]
    resources :replies, :only => [:index, :show, :destroy]
  end
end

app/views/shared/_flash_messages.haml
- if flash[:success]
  .alert.alert-success
    = flash[:success]
    %button.close{'data-dismiss' => 'alert'} x
- if flash[:notice]
  .alert
    = flash[:notice]
    %button.close{'data-dismiss' => 'alert'} x
- if flash[:error]
  .alert.alert-error
    = flash[:error]
    %button.close{'data-dismiss' => 'alert'} x

app/views/shared/_sidebar_login.haml
%section.box
  %header
    = t '.header'
  = link_to t('signup'), signup_path, :class => 'btn success'
  = t 'or'
  = link_to t('login'), login_path, :class => 'btn'

app/views/shared/_sidebar_profile.haml
%section.profile.box
  .clearfix
    .avatar
      = link_avatar_to_person current_user, :size => 64
    .info
      = t '.signed_as'
      %h3= current_user.name
  %hr
  .notifications
    - count = current_user.notifications.unread.count
    = content_tag 'a', :href => notifications_path, :class => (count > 0 ? nil : 'read') do
      %span.count= count
      = t('.unread_notifications')