config/routes.rb
CodeCampo::Application.routes.draw do
  root :to => 'homepage#index'

  get 'signup' => 'users#new', :as => :signup
  get 'login' => 'user_sessions#new', :as => :login
  delete 'logout' => 'user_sessions#destroy', :as => :logout
  resources :users, :only => [:create, :destroy]

  resources :user_sessions, :only => [:create]

  resource :search, :controller => 'search', :only => 'show'

  get '~:name', :controller => 'people', :action => 'show', :as => :person
  resources :notifications, :only => [:index, :destroy] do
    collection do
      put :mark_all_as_read
    end
  end
  resources :topics, :only => [:index, :show, :new, :create, :edit, :update] do
    collection do
      get :newest
      get :my
      get :marked
      get :replied
      get 'tagged/:tag', :action => 'tagged', :as => :tagged, :constraints  => { :tag => /[^\/]+/ }, :format => false
      get :interesting
    end
    member do
      post :mark
      delete :mark, :action => 'unmark'
    end
  end
  resources :replies, :only => [:new, :create, :edit, :update]
  namespace :settings do
    resource :account, :only => [:show, :update]
    resource :password, :only => [:show, :update]
    resource :profile, :only => [:show, :update]
  end

  namespace :admin do
    get '/', :to => 'dashboard#show', :as => 'dashboard'
    resources :fragments, :only => [:index, :edit, :update]
    resource  :site, :only => [:show, :update]
    resources :users, :only => [:index, :show, :destroy]
    resources :topics, :only => [:index, :show, :destroy]
    resources :replies, :only => [:index, :show, :destroy]
  end
end

app/models/profile.rb
class Profile
  include Mongoid::Document

  field :name
  field :url
  field :description

  embedded_in :user

  validates :name, :length => {:in => 3..20, :allow_blank => true}
  validates :url, :length => {:maximum => 100}
  validates :description, :length => {:maximum => 300}

  attr_accessible :name, :url, :description
end

app/controllers/settings/accounts_controller.rb
class Settings::AccountsController < ApplicationController
  before_filter :require_logined
  layout 'settings'

  def show
    logger.info current_user.inspect
  end

  def update
    if current_user.update_attributes params[:user]
      flash[:success] = I18n.t(:success_update)
      redirect_to :action => :show
    else
      render :show
    end
  end
end

app/controllers/settings/passwords_controller.rb
class Settings::PasswordsController < ApplicationController
  before_filter :require_logined
  layout 'settings'

  def show
  end

  def update
    if current_user.update_attributes params[:user]
      flash[:success] = I18n.t(:success_update)
      redirect_to :action => :show
    else
      render :show
    end
  end
end

app/controllers/settings/profiles_controller.rb
class Settings::ProfilesController < ApplicationController
  before_filter :require_logined
  layout 'settings'

  def show
  end

  def update
    if current_user.profile.update_attributes params[:profile]
      flash[:success] = I18n.t(:success_update)
      redirect_to :action => :show
    else
      render :show
    end
  end
end

app/views/settings/profiles/show.haml
%header
  %h3= t '.profile_settings'
= form_for current_user.profile, :url => settings_profile_path, :validate => true do |f|
  %fieldset
    .control-group
      .control-label
        = f.label :avatar
      .controls
        .avatar= image_tag current_user.gravatar_url(:size => 160)
        %p
          = link_to t('.change_email'), settings_account_path
          = '/'
          = link_to t('.go_to_gravatar'), 'http://www.gravatar.com', :rel => 'external'
    .control-group
      .control-label
        = f.label :name
      .controls
        = f.text_field :name, :class => 'span3'
    .control-group
      .control-label
        = f.label :url
      .controls
        = f.text_field :url, :class => 'span3'
    .control-group
      .control-label
        = f.label :description
      .controls
        = f.text_area :description, :rows => 5, :class => 'span6'
    = f.submit t('save'), :class => 'btn primary'